# LOCALHOST
GET http://localhost:3000/contacts 
###
GET http://localhost:3000/contacts/644c40654a331796e277222e
###
GET http://localhost:3000/contacts/644c40744a331796e2772230
###
GET http://localhost:3000/contacts/644c40804a331796e2772232
###
#CREATE CONTACT LOCAL
POST http://localhost:3000/contacts/create-contact HTTP/1.1
Content-Type: application/json

{
    "firstName":"Johnndn",
    "lastName":"Smith",
    "email":"johndoe@example.com",
    "favoriteColor":"blue-updated",
    "birthday":"1990-07-10"
}

###
#UPDATE CONTACT LOCALY
PUT http://localhost:3000/contacts/update/644c40744a331796e2772230 HTTP/1.1
Content-Type: application/json

{
    "firstName":"JanEE Lenyyy11",
    "lastName":"LETS GOOO",
    "email":"janedoe11@example.com",
    "favoriteColor":"green-updated",
    "birthday":"1992-03-15"
}

###
#DELETE CONTACT LOCALY
DELETE http://localhost:3000/contacts/delete/64572c7776d7cf0299ccfffd HTTP/1.1
Content-Type: application/json


###
# DEPLOYMENT
GET https://cse341valencia.onrender.com/contacts
###
GET https://cse341valencia.onrender.com/contacts/644c40654a331796e277222e
###
GET https://cse341valencia.onrender.com/contacts/644c40744a331796e2772230
###
GET https://cse341valencia.onrender.com/contacts/644c40804a331796e2772232

###
#CREATE CONTACT LOCAL #201
POST https://cse341valencia.onrender.com/contacts/create-contact HTTP/1.1
Content-Type: application/json

{
    "firstName":"Johnndn",
    "lastName":"Smith",
    "email":"johndoe@example.com",
    "favoriteColor":"blue-updated",
    "birthday":"1990-07-10"
}

###
#UPDATE CONTACT LOCALY #204
PUT https://cse341valencia.onrender.com/contacts/update/644c40744a331796e2772230 HTTP/1.1
Content-Type: application/json

{
    "firstName":"JanEE Lenyyy11",
    "lastName":"LETS GOOO",
    "email":"janedoe11@example.com",
    "favoriteColor":"green-updated",
    "birthday":"1992-03-15"
}

###
#DELETE CONTACT LOCALY #200
DELETE https://cse341valencia.onrender.com/contacts/delete/64572c7776d7cf0299ccfffd HTTP/1.1
Content-Type: application/json



